apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/kong-net: "true"
    io.kompose.service: kong-migration
  name: kong-migration
spec:
  containers:
    - args:
        - kong
        - migrations
        - bootstrap
      env:
        - name: KONG_PG_HOST
          value: kong-database
        - name: KONG_PG_PASSWORD
          value: kong
      image: kong:1.5
      name: kong-migration
      resources: {}
  restartPolicy: OnFailure
status: {}
